from sqlalchemy import Column, Integer, String, SmallInteger, REAL, FLOAT, UnicodeText, Unicode
from src.db.database import Base
from src.config.settings import get_general_settings
from sqlalchemy.sql import quoted_name


class Request(Base):
    __tablename__ = quoted_name(get_general_settings().request_table, quote=True)

    rordno = Column(Integer, primary_key=True)
    rdate = Column(Integer, nullable=False)
    rlabel = Column(Integer, nullable=False)
    rtest = Column(Integer, nullable=False)
    rinst = Column(SmallInteger)
    rstatus = Column(SmallInteger)
    rlab = Column(SmallInteger)
    rresult = Column(UnicodeText)
    rcommconst = Column(SmallInteger)
    rcommfree = Column(SmallInteger)
    rappdat = Column(Integer)
    rapptim = Column(SmallInteger)
    rbounds = Column(SmallInteger)
    rrerun = Column(SmallInteger)
    rinprof = Column(Integer)
    rphinst = Column(SmallInteger)
    ruser = Column(SmallInteger)
    rdelta = Column(SmallInteger)
    rlocation = Column(SmallInteger)
    rtubenum = Column(SmallInteger, nullable=False)
    rdynamictime = Column(SmallInteger)
    rrun = Column(SmallInteger)
    rtray = Column(Integer)
    rdilution = Column(REAL)
    rresstat = Column(SmallInteger)
    risreruns = Column(SmallInteger)
    rflag = Column(SmallInteger)
    rsort = Column(SmallInteger)
    rpreresult = Column(UnicodeText)
    rgraph = Column(SmallInteger)
    rprint = Column(SmallInteger)
    rlaststatus = Column(SmallInteger)
    rprevtestalert = Column(SmallInteger)
    rcommrunconst = Column(SmallInteger)
    rcommrunfree = Column(SmallInteger)
    rformulainfo = Column(Unicode(140))
    rurgent = Column(SmallInteger)
    rqcstatus = Column(SmallInteger)
    ralert = Column(SmallInteger)
    rautobounds = Column(Integer)
    rtestnum = Column(SmallInteger, nullable=False)
    rorigtest = Column(SmallInteger)
    runique = Column(Integer, nullable=False)
    rtechapp = Column(SmallInteger)
    rparam = Column(Integer)
    rcount = Column(SmallInteger)
    rhead = Column(SmallInteger)
    rprnsort = Column(SmallInteger)
    rprofnum = Column(SmallInteger)
    rhasdist = Column(SmallInteger)
    rperformsite = Column(Integer)
    rinsertdate = Column(Integer)
    rinserttime = Column(SmallInteger)
    risprofile = Column(SmallInteger)
    rphonedist = Column(Integer)
    rnumresult = Column(FLOAT)
    rbillcount = Column(SmallInteger)
    rdiffdist = Column(SmallInteger)
    rboundsvalue = Column(Unicode(1200))
    rmnstatus = Column(SmallInteger)
    risreject = Column(SmallInteger)
    runits = Column(SmallInteger)
    rparam2 = Column(Integer)
    rquantity = Column(REAL)
    ronhold = Column(SmallInteger)
    roverdue = Column(SmallInteger)
    rmainpanel = Column(Integer)
